environment:
  global:
    # Wrapper to ensure extensions are build using the MSVC compiler matching
    # the target Python version and architecture.
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tasks\run_with_env.cmd'

  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  # Upgrade to the latest pip.
  - python -m pip install -U pip setuptools wheel tox
  - python -m pip install -r requirements.txt
  - pyinstaller run.spec

build: off

artifacts:
  - path: build
    name: buiild
  - path: dist
    name: dist
